# This is a basic workflow to help you get started with Actions

name: Firebase Functions deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: ENV Check
        run: |
          if [ "$REACT_APP_FIREBASE_ENV" == "dev" ]
          then
            echo "Building with DEV env vars set"
          elif [ "$REACT_APP_FIREBASE_ENV" == "prod" ]
          then
            echo "Building with PROD env vars set"
          else
            echo "env vars are improperly set, not DEV or PROD."
          fi
        env:
          REACT_APP_FIREBASE_ENV: ${{secrets.REACT_APP_FIREBASE_ENV}}

      # Runs a single command using the runners shell
      # And of course we need to goto our functions folder to deploy
      - name: Install npm packages
        run: |
          npm install
          cd backend
          npm install
          cd ../frontend
          npm install
          npm run build
      # Initilize session with firebase project
      - name: Initialize Firebase Project
        uses: w9jds/firebase-action@master
        with:
          args: use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_OAUTH_CREDENTIALS: ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT_STRINGIFIED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_STRINGIFIED }}
      # Deploying the functions to firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_OAUTH_CREDENTIALS: ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT_STRINGIFIED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_STRINGIFIED }}
