# This is a basic workflow to help you get started with Actions

name: Deploy Food Rescue App to DEV Environment

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_frontend:
    name: 'Deploy Frontend'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout Github Repo'
        uses: actions/checkout@v3
      - name: Install Root Dependencies
        run: npm install
      - name: Install React App Dependencies
        run: |
          cd frontend
          npm install
      - name: Create .env File Locally
        run: |
          cd frontend
          echo "${{secrets.ENV_FRONTEND }}" > .env
        env:
          ENV_FRONTEND: ${{secrets.ENV_FRONTEND}}
      - name: Build React Application
        run: |
          cd frontend
          npm run build
      - name: Initialize Firebase Project
        uses: w9jds/firebase-action@master
        with:
          args: use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy React App
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:react-app-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_backend:
    name: 'Deploy Backend'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout Github Repo'
        uses: actions/checkout@v3
      - name: Install Root Dependencies
        run: npm install
      - name: Install Node App Dependencies
        run: |
          cd backend
          npm install
      - name: Create .env File Locally
        run: |
          cd backend
          echo "${{secrets.ENV_BACKEND }}" > .env
        env:
          ENV_BACKEND: ${{secrets.ENV_BACKEND}}
      - name: Initialize Firebase Project
        uses: w9jds/firebase-action@master
        with:
          args: use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Node API
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:node-api-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
