name: Deploy to Sharing Excess Production Environment

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: echo "The version number is ${{ github.event.inputs.version }}"
      - name: Send Release to Sentry
        uses: dmandrade/sentry-release-github-action@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: foo
          SENTRY_PROJECT: bar
        with:
          version: ${{ github.event.inputs.version }}